#**Importing, Reading and Inspecting the dataset**

In [ ]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
#STEP-2: Autheticate E-Mail ID
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)
#STEP-3: Get File from Drive using file-ID
downloaded = drive.CreateFile({'id':'14YW92TeU4Q-EJNmU_p5KkOOSXkc2jtni'}) # replace the id with id of file you want to access
downloaded.GetContentFile('auto-mpg.xls')

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('auto-mpg.xls')
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [ ]:
# Number of rows and columns 
df.shape

(398, 9)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
mpg,398.0,23.514573,7.815984,9.0,17.500,23.0,29.000,46.6
cylinders,398.0,5.454774,1.701004,3.0,4.000,4.0,8.000,8.0
displacement,398.0,193.425879,104.269838,68.0,104.250,148.5,262.000,455.0
weight,398.0,2970.424623,846.841774,1613.0,2223.750,2803.5,3608.000,5140.0
acceleration,398.0,15.568090,2.757689,8.0,13.825,15.5,17.175,24.8
model year,398.0,76.010050,3.697627,70.0,73.000,76.0,79.000,82.0
origin,398.0,1.572864,0.802055,1.0,1.000,1.0,2.000,3.0

In [ ]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

#a) Dropping the name and origin columns

In [ ]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='object')

In [ ]:
df = pd.DataFrame(df)
df = df.drop(['origin', 'car name'], axis=1)
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year
0,18.0,8,307.0,130,3504,12.0,70
1,15.0,8,350.0,165,3693,11.5,70
2,18.0,8,318.0,150,3436,11.0,70
3,16.0,8,304.0,150,3433,12.0,70
4,17.0,8,302.0,140,3449,10.5,70
...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82
394,44.0,4,97.0,52,2130,24.6,82
395,32.0,4,135.0,84,2295,11.6,82
396,28.0,4,120.0,79,2625,18.6,82
397,31.0,4,119.0,82,2720,19.4,82

# b) Filling up the 'horsepower' columns's null values with mean values of the column

In [ ]:
x = df["horsepower"][0]
type((x))

str

In [ ]:
df['horsepower']

0      130
1      165
2      150
3      150
4      140
      ...
393     86
394     52
395     84
396     79
397     82
Name: horsepower, Length: 398, dtype: object

In [ ]:
l = []
num = []
for i in df['horsepower']:
  try:
    i = int(i)
    num.append(i)
  except:
    pass
df['horsepower'] = df['horsepower'].replace("?",np.mean(num))
df["horsepower"] = df["horsepower"].astype("int64")

In [ ]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year
0,18.0,8,307.0,130,3504,12.0,70
1,15.0,8,350.0,165,3693,11.5,70
2,18.0,8,318.0,150,3436,11.0,70
3,16.0,8,304.0,150,3433,12.0,70
4,17.0,8,302.0,140,3449,10.5,70
...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82
394,44.0,4,97.0,52,2130,24.6,82
395,32.0,4,135.0,84,2295,11.6,82
396,28.0,4,120.0,79,2625,18.6,82
397,31.0,4,119.0,82,2720,19.4,82

# c) Replacing 2 digits with 4 digits

In [ ]:
l = []
for i in df['model year']:
  i = '19'+str(i)
  l.append(int(i))


df['model year'] = l
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year
0,18.0,8,307.0,130,3504,12.0,1970
1,15.0,8,350.0,165,3693,11.5,1970
2,18.0,8,318.0,150,3436,11.0,1970
3,16.0,8,304.0,150,3433,12.0,1970
4,17.0,8,302.0,140,3449,10.5,1970
...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,1982
394,44.0,4,97.0,52,2130,24.6,1982
395,32.0,4,135.0,84,2295,11.6,1982
396,28.0,4,120.0,79,2625,18.6,1982
397,31.0,4,119.0,82,2720,19.4,1982

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    int64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
dtypes: float64(3), int64(4)
memory usage: 21.9 KB

# d) 50/50 splitting the dataset into training and validation set

In [ ]:
X = df.drop(["mpg"],axis=1).values
y = df["mpg"].values

In [ ]:
X

array([[   8. ,  307. ,  130. , 3504. ,   12. , 1970. ],
       [   8. ,  350. ,  165. , 3693. ,   11.5, 1970. ],
       [   8. ,  318. ,  150. , 3436. ,   11. , 1970. ],
       ...,
       [   4. ,  135. ,   84. , 2295. ,   11.6, 1982. ],
       [   4. ,  120. ,   79. , 2625. ,   18.6, 1982. ],
       [   4. ,  119. ,   82. , 2720. ,   19.4, 1982. ]])

In [ ]:
X.shape

(398, 6)

In [ ]:
y

array([18. , 15. , 18. , 16. , 17. , 15. , 14. , 14. , 14. , 15. , 15. ,
       14. , 15. , 14. , 24. , 22. , 18. , 21. , 27. , 26. , 25. , 24. ,
       25. , 26. , 21. , 10. , 10. , 11. ,  9. , 27. , 28. , 25. , 25. ,
       19. , 16. , 17. , 19. , 18. , 14. , 14. , 14. , 14. , 12. , 13. ,
       13. , 18. , 22. , 19. , 18. , 23. , 28. , 30. , 30. , 31. , 35. ,
       27. , 26. , 24. , 25. , 23. , 20. , 21. , 13. , 14. , 15. , 14. ,
       17. , 11. , 13. , 12. , 13. , 19. , 15. , 13. , 13. , 14. , 18. ,
       22. , 21. , 26. , 22. , 28. , 23. , 28. , 27. , 13. , 14. , 13. ,
       14. , 15. , 12. , 13. , 13. , 14. , 13. , 12. , 13. , 18. , 16. ,
       18. , 18. , 23. , 26. , 11. , 12. , 13. , 12. , 18. , 20. , 21. ,
       22. , 18. , 19. , 21. , 26. , 15. , 16. , 29. , 24. , 20. , 19. ,
       15. , 24. , 20. , 11. , 20. , 21. , 19. , 15. , 31. , 26. , 32. ,
       25. , 16. , 16. , 18. , 16. , 13. , 14. , 14. , 14. , 29. , 26. ,
       26. , 31. , 32. , 28. , 24. , 26. , 24. , 26. , 31. , 19. , 18. ,
       15. , 15. , 16. , 15. , 16. , 14. , 17. , 16. , 15. , 18. , 21. ,
       20. , 13. , 29. , 23. , 20. , 23. , 24. , 25. , 24. , 18. , 29. ,
       19. , 23. , 23. , 22. , 25. , 33. , 28. , 25. , 25. , 26. , 27. ,
       17.5, 16. , 15.5, 14.5, 22. , 22. , 24. , 22.5, 29. , 24.5, 29. ,
       33. , 20. , 18. , 18.5, 17.5, 29.5, 32. , 28. , 26.5, 20. , 13. ,
       19. , 19. , 16.5, 16.5, 13. , 13. , 13. , 31.5, 30. , 36. , 25.5,
       33.5, 17.5, 17. , 15.5, 15. , 17.5, 20.5, 19. , 18.5, 16. , 15.5,
       15.5, 16. , 29. , 24.5, 26. , 25.5, 30.5, 33.5, 30. , 30.5, 22. ,
       21.5, 21.5, 43.1, 36.1, 32.8, 39.4, 36.1, 19.9, 19.4, 20.2, 19.2,
       20.5, 20.2, 25.1, 20.5, 19.4, 20.6, 20.8, 18.6, 18.1, 19.2, 17.7,
       18.1, 17.5, 30. , 27.5, 27.2, 30.9, 21.1, 23.2, 23.8, 23.9, 20.3,
       17. , 21.6, 16.2, 31.5, 29.5, 21.5, 19.8, 22.3, 20.2, 20.6, 17. ,
       17.6, 16.5, 18.2, 16.9, 15.5, 19.2, 18.5, 31.9, 34.1, 35.7, 27.4,
       25.4, 23. , 27.2, 23.9, 34.2, 34.5, 31.8, 37.3, 28.4, 28.8, 26.8,
       33.5, 41.5, 38.1, 32.1, 37.2, 28. , 26.4, 24.3, 19.1, 34.3, 29.8,
       31.3, 37. , 32.2, 46.6, 27.9, 40.8, 44.3, 43.4, 36.4, 30. , 44.6,
       40.9, 33.8, 29.8, 32.7, 23.7, 35. , 23.6, 32.4, 27.2, 26.6, 25.8,
       23.5, 30. , 39.1, 39. , 35.1, 32.3, 37. , 37.7, 34.1, 34.7, 34.4,
       29.9, 33. , 34.5, 33.7, 32.4, 32.9, 31.6, 28.1, 30.7, 25.4, 24.2,
       22.4, 26.6, 20.2, 17.6, 28. , 27. , 34. , 31. , 29. , 27. , 24. ,
       23. , 36. , 37. , 31. , 38. , 36. , 36. , 36. , 34. , 38. , 32. ,
       38. , 25. , 38. , 26. , 22. , 32. , 36. , 27. , 27. , 44. , 32. ,
       28. , 31. ])

In [ ]:
y.shape

(398,)

In [ ]:
from sklearn.preprocessing import StandardScaler
st = StandardScaler()
X = st.fit_transform(X)
# y = np.array(y)
# y = st.fit_transform(y.reshape(-1, 1))

In [ ]:
X

array([[ 1.49819126,  1.0906037 ,  0.66938081,  0.63086987, -1.29549834,
        -1.62742629],
       [ 1.49819126,  1.5035143 ,  1.58678287,  0.85433297, -1.47703779,
        -1.62742629],
       [ 1.49819126,  1.19623199,  1.19361056,  0.55047045, -1.65857724,
        -1.62742629],
       ...,
       [-0.85632057, -0.56103873, -0.53634763, -0.79858454, -1.4407299 ,
         1.62198339],
       [-0.85632057, -0.70507731, -0.66740507, -0.40841088,  1.10082237,
         1.62198339],
       [-0.85632057, -0.71467988, -0.5887706 , -0.29608816,  1.39128549,
         1.62198339]])

In [ ]:
X.shape

(398, 6)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.50, random_state = 40)

In [ ]:
a = len(X_train) + len(y_train) 
b = len(X_test) + len(y_test)
print('Training set length: {} | Testing set length: {}'.format(a,b))
print('X Training set length:',len(X_train))
print('Y Training set length:',len(y_train))
print('X Testing set length:',len(X_test))
print('Y Testing set length:',len(y_test))

Training set length: 398 | Testing set length: 398
X Training set length: 199
Y Training set length: 199
X Testing set length: 199
Y Testing set length: 199

In [ ]:
X_train

array([[-1.44494853, -1.18520592, -0.3790787 , -1.00076544, -0.75088   ,
        -0.81507387],
       [ 1.49819126,  1.98364292,  2.24207007,  1.71626206, -1.1139589 ,
        -1.08585801],
       [-0.85632057, -0.69547474,  0.14515105, -0.36702882, -0.56934055,
        -0.81507387],
       ...,
       [ 1.49819126,  2.36774581,  2.89735726,  1.58620417, -2.56627448,
        -1.62742629],
       [-0.85632057, -0.68587217, -0.22180977, -0.79267282, -0.02472221,
         0.26806269],
       [-0.85632057, -0.99315448, -1.47996118, -0.75129076,  2.95252475,
         1.08041511]])

In [ ]:
X_train.shape

(199, 6)

In [ ]:
y_train

array([18. , 13. , 24. , 21. , 13. , 34.4, 29.8, 15. , 19. , 26. , 20.2,
       22. , 37.3, 27.9, 23.8, 30.7, 13. , 14. , 22. , 19. , 27. , 35.1,
       15. , 24. , 19. , 16. , 28. , 23. , 35. , 26. , 18. , 26. , 17. ,
       29.5, 26. , 14. , 21.5, 18. , 13. , 46.6, 21. , 43.1, 36. , 19. ,
       15. , 34.2, 30.9, 24.5, 15. , 13. , 14. , 25.8, 21. , 27.5, 31. ,
       14. , 25. , 25. , 25. , 21. , 26.6, 37. , 28. , 15. , 14. , 27.4,
       17. , 11. , 19. , 15. , 34. , 23. , 17.7, 32. , 10. , 21.5, 20. ,
       21.5, 26. , 23.5, 41.5, 16. , 13. , 18.6, 20.2, 24.2, 23.2, 13. ,
       15.5, 32.4, 23. , 18. , 22. , 39.4, 16. , 30. , 24.5, 21. , 32. ,
       18. , 18. , 11. , 24. , 21. , 15.5, 34.7, 21.6, 27. , 25. , 39. ,
       13. , 16.2, 19.9, 20.2, 15. , 20. , 19.4, 18.5, 36. , 36. , 32. ,
       27. , 13. , 28. , 25. , 26.5, 36.1, 36. , 16. , 23.6, 15. , 15. ,
       29. , 14. , 25.5, 19. , 28. , 32.4, 24. , 31. , 16. , 27. , 16.5,
       18. , 22. , 29. , 30. , 31.5, 26. , 12. , 18. , 25.4, 33.5, 27. ,
       22. , 20. , 22.4, 25. , 20.5, 39.1, 23.9, 20. , 28. , 37. , 19. ,
       22. , 38. , 20. , 33.7, 28. , 32. , 25. , 17.5, 27. , 12. , 37.7,
       21.1, 20. , 16. , 14. , 44.6, 33. , 28.4, 15. , 13. , 13. , 27. ,
       40.9, 14. , 26. , 26. , 36.4, 27.2, 24. , 28.8, 20. , 14. , 25.5,
       43.4])

In [ ]:
y_train.shape

(199,)

# e) Training the keras sequential model

In [ ]:
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.activations import relu, softmax
from tensorflow.keras.losses import BinaryCrossentropy, MeanSquaredError
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam, RMSprop
import tensorflow as tf

In [ ]:
model = tf.keras.Sequential([
    Dense(units = 30, activation = relu, input_shape = [X_train.shape[1]]),
    Dense(units = 20, activation = relu),
    Dense(units = 1)
    ])

In [ ]:
model.summary()

Model: "sequential_20"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_60 (Dense)            (None, 30)                210

 dense_61 (Dense)            (None, 20)                620

 dense_62 (Dense)            (None, 1)                 21

=================================================================
Total params: 851
Trainable params: 851
Non-trainable params: 0
_________________________________________________________________

In [ ]:
model.compile(loss = 'mse', optimizer = RMSprop(0.001), metrics = ['mae','mse'])

In [ ]:
history = model.fit(X_train, y_train, epochs = 100,validation_data=(X_test, y_test))

Epoch 1/100
7/7 [==============================] - 1s 36ms/step - loss: 598.3011 - mae: 23.1011 - mse: 598.3011 - val_loss: 562.2723 - val_mae: 22.3388 - val_mse: 562.2723
Epoch 2/100
7/7 [==============================] - 0s 8ms/step - loss: 581.3430 - mae: 22.7209 - mse: 581.3430 - val_loss: 547.5125 - val_mae: 21.9828 - val_mse: 547.5125
Epoch 3/100
7/7 [==============================] - 0s 7ms/step - loss: 566.0638 - mae: 22.3626 - mse: 566.0638 - val_loss: 529.8566 - val_mae: 21.5671 - val_mse: 529.8566
Epoch 4/100
7/7 [==============================] - 0s 7ms/step - loss: 548.2863 - mae: 21.9531 - mse: 548.2863 - val_loss: 510.8956 - val_mae: 21.1203 - val_mse: 510.8956
Epoch 5/100
7/7 [==============================] - 0s 7ms/step - loss: 529.4192 - mae: 21.5154 - mse: 529.4192 - val_loss: 491.5301 - val_mae: 20.6527 - val_mse: 491.5301
Epoch 6/100
7/7 [==============================] - 0s 9ms/step - loss: 510.1918 - mae: 21.0635 - mse: 510.1918 - val_loss: 471.4330 - val_mae: 20.1573 - val_mse: 471.4330
Epoch 7/100
7/7 [==============================] - 0s 13ms/step - loss: 489.9764 - mae: 20.5741 - mse: 489.9764 - val_loss: 450.6781 - val_mae: 19.6412 - val_mse: 450.6781
Epoch 8/100
7/7 [==============================] - 0s 7ms/step - loss: 468.8482 - mae: 20.0658 - mse: 468.8482 - val_loss: 429.6508 - val_mae: 19.0885 - val_mse: 429.6508
Epoch 9/100
7/7 [==============================] - 0s 7ms/step - loss: 447.3782 - mae: 19.5174 - mse: 447.3782 - val_loss: 407.2865 - val_mae: 18.4777 - val_mse: 407.2865
Epoch 10/100
7/7 [==============================] - 0s 7ms/step - loss: 424.5627 - mae: 18.9137 - mse: 424.5627 - val_loss: 383.2189 - val_mae: 17.8282 - val_mse: 383.2189
Epoch 11/100
7/7 [==============================] - 0s 7ms/step - loss: 399.7076 - mae: 18.2631 - mse: 399.7076 - val_loss: 356.8731 - val_mae: 17.1154 - val_mse: 356.8731
Epoch 12/100
7/7 [==============================] - 0s 7ms/step - loss: 372.8430 - mae: 17.5776 - mse: 372.8430 - val_loss: 331.0684 - val_mae: 16.3702 - val_mse: 331.0684
Epoch 13/100
7/7 [==============================] - 0s 9ms/step - loss: 346.2857 - mae: 16.8670 - mse: 346.2857 - val_loss: 303.9804 - val_mae: 15.6147 - val_mse: 303.9804
Epoch 14/100
7/7 [==============================] - 0s 7ms/step - loss: 318.5371 - mae: 16.1273 - mse: 318.5371 - val_loss: 277.9990 - val_mae: 14.8835 - val_mse: 277.9990
Epoch 15/100
7/7 [==============================] - 0s 7ms/step - loss: 291.1046 - mae: 15.3988 - mse: 291.1046 - val_loss: 249.1654 - val_mae: 14.0395 - val_mse: 249.1654
Epoch 16/100
7/7 [==============================] - 0s 7ms/step - loss: 261.7065 - mae: 14.5646 - mse: 261.7065 - val_loss: 223.3565 - val_mae: 13.2605 - val_mse: 223.3565
Epoch 17/100
7/7 [==============================] - 0s 7ms/step - loss: 234.6388 - mae: 13.7680 - mse: 234.6388 - val_loss: 195.5439 - val_mae: 12.3946 - val_mse: 195.5439
Epoch 18/100
7/7 [==============================] - 0s 8ms/step - loss: 205.8704 - mae: 12.8707 - mse: 205.8704 - val_loss: 170.5477 - val_mae: 11.5532 - val_mse: 170.5477
Epoch 19/100
7/7 [==============================] - 0s 10ms/step - loss: 179.3755 - mae: 11.9724 - mse: 179.3755 - val_loss: 146.5298 - val_mae: 10.6883 - val_mse: 146.5298
Epoch 20/100
7/7 [==============================] - 0s 7ms/step - loss: 153.7234 - mae: 11.0639 - mse: 153.7234 - val_loss: 122.3018 - val_mae: 9.7331 - val_mse: 122.3018
Epoch 21/100
7/7 [==============================] - 0s 7ms/step - loss: 128.8352 - mae: 10.0686 - mse: 128.8352 - val_loss: 101.8033 - val_mae: 8.8250 - val_mse: 101.8033
Epoch 22/100
7/7 [==============================] - 0s 9ms/step - loss: 107.2546 - mae: 9.1341 - mse: 107.2546 - val_loss: 84.1915 - val_mae: 7.9530 - val_mse: 84.1915
Epoch 23/100
7/7 [==============================] - 0s 9ms/step - loss: 88.5111 - mae: 8.1841 - mse: 88.5111 - val_loss: 68.8594 - val_mae: 7.0858 - val_mse: 68.8594
Epoch 24/100
7/7 [==============================] - 0s 7ms/step - loss: 72.4650 - mae: 7.2822 - mse: 72.4650 - val_loss: 58.6041 - val_mae: 6.4302 - val_mse: 58.6041
Epoch 25/100
7/7 [==============================] - 0s 7ms/step - loss: 61.0802 - mae: 6.5812 - mse: 61.0802 - val_loss: 50.1509 - val_mae: 5.8463 - val_mse: 50.1509
Epoch 26/100
7/7 [==============================] - 0s 7ms/step - loss: 51.9543 - mae: 5.9536 - mse: 51.9543 - val_loss: 44.5425 - val_mae: 5.3565 - val_mse: 44.5425
Epoch 27/100
7/7 [==============================] - 0s 7ms/step - loss: 45.6932 - mae: 5.4657 - mse: 45.6932 - val_loss: 41.1942 - val_mae: 5.0455 - val_mse: 41.1942
Epoch 28/100
7/7 [==============================] - 0s 10ms/step - loss: 41.6772 - mae: 5.1766 - mse: 41.6772 - val_loss: 39.0252 - val_mae: 4.8735 - val_mse: 39.0252
Epoch 29/100
7/7 [==============================] - 0s 9ms/step - loss: 39.0212 - mae: 4.9716 - mse: 39.0212 - val_loss: 37.2934 - val_mae: 4.7455 - val_mse: 37.2934
Epoch 30/100
7/7 [==============================] - 0s 7ms/step - loss: 36.9691 - mae: 4.8491 - mse: 36.9691 - val_loss: 35.4681 - val_mae: 4.6016 - val_mse: 35.4681
Epoch 31/100
7/7 [==============================] - 0s 7ms/step - loss: 35.1311 - mae: 4.6904 - mse: 35.1311 - val_loss: 34.3735 - val_mae: 4.5113 - val_mse: 34.3735
Epoch 32/100
7/7 [==============================] - 0s 7ms/step - loss: 33.3329 - mae: 4.5691 - mse: 33.3329 - val_loss: 32.9091 - val_mae: 4.4109 - val_mse: 32.9091
Epoch 33/100
7/7 [==============================] - 0s 8ms/step - loss: 31.7830 - mae: 4.4426 - mse: 31.7830 - val_loss: 30.5999 - val_mae: 4.2333 - val_mse: 30.5999
Epoch 34/100
7/7 [==============================] - 0s 7ms/step - loss: 30.1899 - mae: 4.3163 - mse: 30.1899 - val_loss: 29.1182 - val_mae: 4.1224 - val_mse: 29.1182
Epoch 35/100
7/7 [==============================] - 0s 7ms/step - loss: 28.4364 - mae: 4.1700 - mse: 28.4364 - val_loss: 26.8686 - val_mae: 3.9353 - val_mse: 26.8686
Epoch 36/100
7/7 [==============================] - 0s 9ms/step - loss: 27.3445 - mae: 4.0540 - mse: 27.3445 - val_loss: 25.3675 - val_mae: 3.8220 - val_mse: 25.3675
Epoch 37/100
7/7 [==============================] - 0s 8ms/step - loss: 26.0571 - mae: 3.9752 - mse: 26.0571 - val_loss: 24.2296 - val_mae: 3.7301 - val_mse: 24.2296
Epoch 38/100
7/7 [==============================] - 0s 7ms/step - loss: 24.8729 - mae: 3.8608 - mse: 24.8729 - val_loss: 23.0809 - val_mae: 3.6372 - val_mse: 23.0809
Epoch 39/100
7/7 [==============================] - 0s 14ms/step - loss: 23.8358 - mae: 3.7630 - mse: 23.8358 - val_loss: 22.8057 - val_mae: 3.6078 - val_mse: 22.8057
Epoch 40/100
7/7 [==============================] - 0s 11ms/step - loss: 23.0253 - mae: 3.7149 - mse: 23.0253 - val_loss: 21.4697 - val_mae: 3.5016 - val_mse: 21.4697
Epoch 41/100
7/7 [==============================] - 0s 12ms/step - loss: 22.1400 - mae: 3.6216 - mse: 22.1400 - val_loss: 20.5857 - val_mae: 3.4353 - val_mse: 20.5857
Epoch 42/100
7/7 [==============================] - 0s 12ms/step - loss: 21.2497 - mae: 3.5416 - mse: 21.2497 - val_loss: 20.0815 - val_mae: 3.3945 - val_mse: 20.0815
Epoch 43/100
7/7 [==============================] - 0s 10ms/step - loss: 20.4293 - mae: 3.4889 - mse: 20.4293 - val_loss: 19.4718 - val_mae: 3.3250 - val_mse: 19.4718
Epoch 44/100
7/7 [==============================] - 0s 7ms/step - loss: 19.6768 - mae: 3.4235 - mse: 19.6768 - val_loss: 18.3974 - val_mae: 3.2456 - val_mse: 18.3974
Epoch 45/100
7/7 [==============================] - 0s 9ms/step - loss: 18.7481 - mae: 3.3352 - mse: 18.7481 - val_loss: 17.5207 - val_mae: 3.1787 - val_mse: 17.5207
Epoch 46/100
7/7 [==============================] - 0s 7ms/step - loss: 18.1967 - mae: 3.2724 - mse: 18.1967 - val_loss: 16.5675 - val_mae: 3.0864 - val_mse: 16.5675
Epoch 47/100
7/7 [==============================] - 0s 9ms/step - loss: 17.4130 - mae: 3.1807 - mse: 17.4130 - val_loss: 15.8336 - val_mae: 3.0206 - val_mse: 15.8336
Epoch 48/100
7/7 [==============================] - 0s 9ms/step - loss: 16.8820 - mae: 3.1365 - mse: 16.8820 - val_loss: 15.9528 - val_mae: 3.0214 - val_mse: 15.9528
Epoch 49/100
7/7 [==============================] - 0s 7ms/step - loss: 16.2529 - mae: 3.0753 - mse: 16.2529 - val_loss: 15.3386 - val_mae: 2.9645 - val_mse: 15.3386
Epoch 50/100
7/7 [==============================] - 0s 7ms/step - loss: 15.7760 - mae: 3.0244 - mse: 15.7760 - val_loss: 14.5584 - val_mae: 2.9066 - val_mse: 14.5584
Epoch 51/100
7/7 [==============================] - 0s 7ms/step - loss: 15.3095 - mae: 2.9531 - mse: 15.3095 - val_loss: 14.1260 - val_mae: 2.8651 - val_mse: 14.1260
Epoch 52/100
7/7 [==============================] - 0s 10ms/step - loss: 14.9104 - mae: 2.9246 - mse: 14.9104 - val_loss: 13.7054 - val_mae: 2.8242 - val_mse: 13.7054
Epoch 53/100
7/7 [==============================] - 0s 9ms/step - loss: 14.4809 - mae: 2.8705 - mse: 14.4809 - val_loss: 13.9442 - val_mae: 2.8398 - val_mse: 13.9442
Epoch 54/100
7/7 [==============================] - 0s 9ms/step - loss: 14.1202 - mae: 2.8499 - mse: 14.1202 - val_loss: 12.9134 - val_mae: 2.7337 - val_mse: 12.9134
Epoch 55/100
7/7 [==============================] - 0s 7ms/step - loss: 13.8845 - mae: 2.7808 - mse: 13.8845 - val_loss: 12.6145 - val_mae: 2.6812 - val_mse: 12.6145
Epoch 56/100
7/7 [==============================] - 0s 8ms/step - loss: 13.5053 - mae: 2.7700 - mse: 13.5053 - val_loss: 12.2323 - val_mae: 2.6409 - val_mse: 12.2323
Epoch 57/100
7/7 [==============================] - 0s 7ms/step - loss: 13.1749 - mae: 2.6874 - mse: 13.1749 - val_loss: 11.8199 - val_mae: 2.5811 - val_mse: 11.8199
Epoch 58/100
7/7 [==============================] - 0s 9ms/step - loss: 12.8619 - mae: 2.6714 - mse: 12.8619 - val_loss: 11.6872 - val_mae: 2.5754 - val_mse: 11.6872
Epoch 59/100
7/7 [==============================] - 0s 7ms/step - loss: 12.4699 - mae: 2.6240 - mse: 12.4699 - val_loss: 11.3409 - val_mae: 2.5137 - val_mse: 11.3409
Epoch 60/100
7/7 [==============================] - 0s 7ms/step - loss: 12.3572 - mae: 2.5944 - mse: 12.3572 - val_loss: 11.2234 - val_mae: 2.4999 - val_mse: 11.2234
Epoch 61/100
7/7 [==============================] - 0s 7ms/step - loss: 12.0231 - mae: 2.5546 - mse: 12.0231 - val_loss: 11.3337 - val_mae: 2.5097 - val_mse: 11.3337
Epoch 62/100
7/7 [==============================] - 0s 9ms/step - loss: 11.8458 - mae: 2.5331 - mse: 11.8458 - val_loss: 11.5356 - val_mae: 2.5261 - val_mse: 11.5356
Epoch 63/100
7/7 [==============================] - 0s 7ms/step - loss: 11.8595 - mae: 2.5292 - mse: 11.8595 - val_loss: 11.2106 - val_mae: 2.4967 - val_mse: 11.2106
Epoch 64/100
7/7 [==============================] - 0s 7ms/step - loss: 11.5878 - mae: 2.4912 - mse: 11.5878 - val_loss: 10.6571 - val_mae: 2.4372 - val_mse: 10.6571
Epoch 65/100
7/7 [==============================] - 0s 8ms/step - loss: 11.3250 - mae: 2.4429 - mse: 11.3250 - val_loss: 10.8969 - val_mae: 2.4621 - val_mse: 10.8969
Epoch 66/100
7/7 [==============================] - 0s 7ms/step - loss: 11.2057 - mae: 2.4523 - mse: 11.2057 - val_loss: 10.9848 - val_mae: 2.4993 - val_mse: 10.9848
Epoch 67/100
7/7 [==============================] - 0s 7ms/step - loss: 11.0249 - mae: 2.4167 - mse: 11.0249 - val_loss: 10.9831 - val_mae: 2.4789 - val_mse: 10.9831
Epoch 68/100
7/7 [==============================] - 0s 9ms/step - loss: 10.9417 - mae: 2.4242 - mse: 10.9417 - val_loss: 10.2156 - val_mae: 2.4011 - val_mse: 10.2156
Epoch 69/100
7/7 [==============================] - 0s 9ms/step - loss: 10.7097 - mae: 2.3691 - mse: 10.7097 - val_loss: 10.2713 - val_mae: 2.4074 - val_mse: 10.2713
Epoch 70/100
7/7 [==============================] - 0s 8ms/step - loss: 10.7732 - mae: 2.3992 - mse: 10.7732 - val_loss: 9.8286 - val_mae: 2.3469 - val_mse: 9.8286
Epoch 71/100
7/7 [==============================] - 0s 7ms/step - loss: 10.6735 - mae: 2.3645 - mse: 10.6735 - val_loss: 9.7274 - val_mae: 2.3262 - val_mse: 9.7274
Epoch 72/100
7/7 [==============================] - 0s 7ms/step - loss: 10.4340 - mae: 2.3382 - mse: 10.4340 - val_loss: 9.6393 - val_mae: 2.3263 - val_mse: 9.6393
Epoch 73/100
7/7 [==============================] - 0s 7ms/step - loss: 10.4093 - mae: 2.3347 - mse: 10.4093 - val_loss: 9.7863 - val_mae: 2.3424 - val_mse: 9.7863
Epoch 74/100
7/7 [==============================] - 0s 8ms/step - loss: 10.2004 - mae: 2.3113 - mse: 10.2004 - val_loss: 10.2230 - val_mae: 2.3835 - val_mse: 10.2230
Epoch 75/100
7/7 [==============================] - 0s 7ms/step - loss: 10.2287 - mae: 2.3221 - mse: 10.2287 - val_loss: 9.4496 - val_mae: 2.3017 - val_mse: 9.4496
Epoch 76/100
7/7 [==============================] - 0s 9ms/step - loss: 10.1082 - mae: 2.3084 - mse: 10.1082 - val_loss: 9.4323 - val_mae: 2.3162 - val_mse: 9.4323
Epoch 77/100
7/7 [==============================] - 0s 8ms/step - loss: 10.1845 - mae: 2.3328 - mse: 10.1845 - val_loss: 9.4346 - val_mae: 2.3169 - val_mse: 9.4346
Epoch 78/100
7/7 [==============================] - 0s 7ms/step - loss: 9.9070 - mae: 2.2914 - mse: 9.9070 - val_loss: 9.3446 - val_mae: 2.3035 - val_mse: 9.3446
Epoch 79/100
7/7 [==============================] - 0s 7ms/step - loss: 9.9449 - mae: 2.2799 - mse: 9.9449 - val_loss: 9.1882 - val_mae: 2.2801 - val_mse: 9.1882
Epoch 80/100
7/7 [==============================] - 0s 7ms/step - loss: 9.7777 - mae: 2.2570 - mse: 9.7777 - val_loss: 10.1295 - val_mae: 2.3914 - val_mse: 10.1295
Epoch 81/100
7/7 [==============================] - 0s 7ms/step - loss: 9.7942 - mae: 2.2759 - mse: 9.7942 - val_loss: 9.1080 - val_mae: 2.2751 - val_mse: 9.1080
Epoch 82/100
7/7 [==============================] - 0s 8ms/step - loss: 9.6479 - mae: 2.2509 - mse: 9.6479 - val_loss: 9.2491 - val_mae: 2.2926 - val_mse: 9.2491
Epoch 83/100
7/7 [==============================] - 0s 7ms/step - loss: 9.5505 - mae: 2.2432 - mse: 9.5505 - val_loss: 9.6382 - val_mae: 2.3389 - val_mse: 9.6382
Epoch 84/100
7/7 [==============================] - 0s 7ms/step - loss: 9.6188 - mae: 2.2529 - mse: 9.6188 - val_loss: 9.1544 - val_mae: 2.2806 - val_mse: 9.1544
Epoch 85/100
7/7 [==============================] - 0s 7ms/step - loss: 9.4420 - mae: 2.2137 - mse: 9.4420 - val_loss: 9.1791 - val_mae: 2.2968 - val_mse: 9.1791
Epoch 86/100
7/7 [==============================] - 0s 7ms/step - loss: 9.4079 - mae: 2.2058 - mse: 9.4079 - val_loss: 9.1396 - val_mae: 2.2902 - val_mse: 9.1396
Epoch 87/100
7/7 [==============================] - 0s 9ms/step - loss: 9.6146 - mae: 2.2168 - mse: 9.6146 - val_loss: 8.9437 - val_mae: 2.2636 - val_mse: 8.9437
Epoch 88/100
7/7 [==============================] - 0s 9ms/step - loss: 9.4233 - mae: 2.2108 - mse: 9.4233 - val_loss: 9.1656 - val_mae: 2.2951 - val_mse: 9.1656
Epoch 89/100
7/7 [==============================] - 0s 8ms/step - loss: 9.2607 - mae: 2.1784 - mse: 9.2607 - val_loss: 8.9209 - val_mae: 2.2542 - val_mse: 8.9209
Epoch 90/100
7/7 [==============================] - 0s 7ms/step - loss: 9.2877 - mae: 2.1800 - mse: 9.2877 - val_loss: 9.6041 - val_mae: 2.3308 - val_mse: 9.6041
Epoch 91/100
7/7 [==============================] - 0s 8ms/step - loss: 9.3107 - mae: 2.1890 - mse: 9.3107 - val_loss: 8.8922 - val_mae: 2.2634 - val_mse: 8.8922
Epoch 92/100
7/7 [==============================] - 0s 9ms/step - loss: 9.2936 - mae: 2.2046 - mse: 9.2936 - val_loss: 8.7067 - val_mae: 2.2418 - val_mse: 8.7067
Epoch 93/100
7/7 [==============================] - 0s 7ms/step - loss: 9.0109 - mae: 2.1497 - mse: 9.0109 - val_loss: 9.6298 - val_mae: 2.3413 - val_mse: 9.6298
Epoch 94/100
7/7 [==============================] - 0s 7ms/step - loss: 9.0780 - mae: 2.1723 - mse: 9.0780 - val_loss: 8.7681 - val_mae: 2.2563 - val_mse: 8.7681
Epoch 95/100
7/7 [==============================] - 0s 7ms/step - loss: 8.9343 - mae: 2.1402 - mse: 8.9343 - val_loss: 8.8210 - val_mae: 2.2560 - val_mse: 8.8210
Epoch 96/100
7/7 [==============================] - 0s 7ms/step - loss: 8.9758 - mae: 2.1674 - mse: 8.9758 - val_loss: 8.6354 - val_mae: 2.2320 - val_mse: 8.6354
Epoch 97/100
7/7 [==============================] - 0s 8ms/step - loss: 9.0878 - mae: 2.1568 - mse: 9.0878 - val_loss: 8.5902 - val_mae: 2.2266 - val_mse: 8.5902
Epoch 98/100
7/7 [==============================] - 0s 8ms/step - loss: 8.9807 - mae: 2.1255 - mse: 8.9807 - val_loss: 8.7256 - val_mae: 2.2425 - val_mse: 8.7256
Epoch 99/100
7/7 [==============================] - 0s 7ms/step - loss: 8.8949 - mae: 2.1316 - mse: 8.8949 - val_loss: 8.5508 - val_mae: 2.2238 - val_mse: 8.5508
Epoch 100/100
7/7 [==============================] - 0s 9ms/step - loss: 8.7513 - mae: 2.1125 - mse: 8.7513 - val_loss: 8.6429 - val_mae: 2.2383 - val_mse: 8.6429

In [ ]:
y_pred = model.predict(X_test)

7/7 [==============================] - 0s 2ms/step

In [ ]:
pd.DataFrame(list(zip(y_test,y_pred)), columns = ['Actual Values', 'Predicted Values'])

     Actual Values Predicted Values
0             26.0      [30.302855]
1             18.0      [14.209573]
2             22.0       [22.64322]
3             32.8       [35.36071]
4             24.0      [25.982405]
..             ...              ...
194           20.0      [17.897125]
195           37.2      [35.831127]
196           18.0      [22.218996]
197           14.0     [14.3778925]
198           44.3       [37.64377]

[199 rows x 2 columns]

In [ ]:
from sklearn.metrics import r2_score

r2_score(y_test, y_pred)

0.8554930833886697

In [ ]:
X_test

array([[-0.85632057, -1.09878277, -0.98194292, -1.19112289, -0.02472221,
        -0.54428973],
       [ 0.32093534,  0.30319277,  0.01409361,  0.75974542,  0.33835669,
        -0.54428973],
       [-0.85632057, -0.69547474, -0.74603953, -0.54319814,  0.88297504,
        -1.08585801],
       ...,
       [ 0.32093534,  0.54325708, -0.69361655,  0.71363398,  1.97221172,
        -0.00272145],
       [ 1.49819126,  1.19623199,  1.19361056,  1.33081778, -0.93241945,
        -1.35664215],
       [-0.85632057, -0.99315448, -1.47996118, -1.04687687,  2.22636695,
         1.08041511]])

#f) Query & Prediction

In [ ]:
# initializing the data
data = [[6,2170,502,3164,4.2,2022], 
        [12,6498,730,3472,3.2,2022], 
        [8,3902,986,3020,2.5,2022], 
        [8,6162,670,3721,2.6,2022], 
        [4,122,181,2496,8.3,2022], 
        [6,3232,155,3232,11.5,1969], 
        [3,598,89,1550,10.1,2022], 
        [3,900,50,642,5.8,2022], 
        [4,1189,60,2355,28.1,1964], 
        [4,201,40,2265,32,1908], 
        ]
  
newDF = pd.DataFrame(data, columns=['Cylinder', 'Displacement','Horse Power', 'Weight','Acceleration', 'Year'])
  
# print dataframe.
newDF

   Cylinder  Displacement  Horse Power  Weight  Acceleration  Year
0         6          2170          502    3164           4.2  2022
1        12          6498          730    3472           3.2  2022
2         8          3902          986    3020           2.5  2022
3         8          6162          670    3721           2.6  2022
4         4           122          181    2496           8.3  2022
5         6          3232          155    3232          11.5  1969
6         3           598           89    1550          10.1  2022
7         3           900           50     642           5.8  2022
8         4          1189           60    2355          28.1  1964
9         4           201           40    2265          32.0  1908

In [ ]:
model.predict(newDF)

1/1 [==============================] - 0s 49ms/step

array([[12741.342],
       [20010.14 ],
       [12367.532],
       [19445.826],
       [14401.333],
       [13483.919],
       [12343.692],
       [12513.233],
       [12128.254],
       [13482.612]], dtype=float32)